version: '3.1'

volumes:
  psql_data:
    driver: local

services:
  redis:
    image: redis
    container_name: relay-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - relaydb

  db:
    image: postgres
    container_name: relay-db
    restart: always
    volumes:
      - 'psql_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - relaydb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    container_name: relay-adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8093:8080'
    networks:
      - relaydb
    environment:
      ADMINER_PLUGINS: tables-filter tinymce

networks:
  relaydb:
    name: relaydb
    driver: bridge
